"""fixed ownership field on form_record to 20 max length string

Revision ID: 304a017368a6
Revises: b1ec6b186558
Create Date: 2024-09-06 18:28:38.921729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304a017368a6'
down_revision = 'b1ec6b186558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_record', schema=None) as batch_op:
        batch_op.alter_column('ownership',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_record', schema=None) as batch_op:
        batch_op.alter_column('ownership',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###
