"""update form_records table

Revision ID: 7ab8b9984561
Revises: 486d03c94476
Create Date: 2024-09-05 17:00:57.940940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab8b9984561'
down_revision = '486d03c94476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_record', schema=None) as batch_op:
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
