"""add dontKnowBloodPressure to form_record

Revision ID: b1ec6b186558
Revises: 9e408994654e
Create Date: 2024-09-06 18:02:47.985670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ec6b186558'
down_revision = '9e408994654e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dontKnowBloodPressure', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_record', schema=None) as batch_op:
        batch_op.drop_column('dontKnowBloodPressure')

    # ### end Alembic commands ###
